trigger:
  branches:
    include:
    - master
  paths:
    include:
    - modules/opc-ua-server/*
    - templates/azure-pipelines-module-build.yml

pr:
  autoCancel: true

jobs:
- template: ../../templates/azure-pipelines-module-build.yml
  parameters:
    registryName: $(registryName)
    repositoryName: offline-dashboarding
    imageName: opc-ua-server
    variableGroupName: edge-deployment-settings
    workingDirectory: ./modules/opc-ua-server
