{
 "title": "Production at a glance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "1400" },
   {
    "name": "Source",
    "label": "Site",
    "query": "from(bucket: \"telemetry\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r._measurement == \"DeviceData\"\n  )\n\n|> keep(columns:[\"Source\"])\n  |> distinct(column: \"Source\")\n\n\n"
   }
  ]
 },
 "panels": [
  { "title": "[[Source]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Source" },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n\r\n \r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n  \r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n  |> yield(name: \"Availability\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Quality",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n \r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n  |> yield(name: \"Quality\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Performance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n  |> yield(name: \"Performance\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 1 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "OEE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n    \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n  |> yield(name: \"OEE\")\r\n"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "%" }
   ],
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n  |> cumulativeSum()\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Bad Items\"}))\r\n  |> cumulativeSum()\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> cumulativeSum()\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> cumulativeSum()\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n\r\n  \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\n\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\n\r\n\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n\r\nOEE\r\n|>yield(name: \"OEE\")\r\n\r\nAvailability\r\n|>yield(name: \"Availability\")\r\n\r\nQuality\r\n|>yield(name: \"Quality\")\r\n\r\nPerformance\r\n|>yield(name: \"Performance\")\r\n\r\n \r\n   \r\n RunStatus=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n     _field: \"Running\"\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: max)\r\n  |> yield(name: \"Run Status\") "
    }
   ]
  },
  {
   "title": "Throughput vs Quality",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "%" }
   ],
   "targets": [
    {
     "query": "\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n  |> yield(name: \"Good Items\")\r\n  |> cumulativeSum()\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Bad Items\"}))\r\n  |> yield(name: \"Bad Items\")\r\n  |> cumulativeSum()\r\n\r\n  \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\n\r\n\r\nQuality\r\n|>yield(name: \"Quality\")\r\n\n\r\nIdealRunrate=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"IdealRunrate\"\r\n    }))\r\n  |> yield(name: \"IdealRunrate\")\r\n \r\n  "
    }
   ]
  },
  { "title": "[[Source]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n\r\n \r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n  \r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n  |> yield(name: \"Availability\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 20 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Quality",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 20 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n \r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n  |> yield(name: \"Quality\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 20 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Performance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n  |> yield(name: \"Performance\")\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 20 },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "OEE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n    \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n  |> yield(name: \"OEE\")\r\n"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit", "label": "%" }
   ],
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"csv\"\r\n\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\ndummyRecordCsv = \"#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string\\n#group,false,false,true,true,false,false,true,true,true\\n#default,_result,,,,,,,,\\n,result,table,_start,_stop,_time,_value,Source,_field,_measurement\\n,,0,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,2030-01-01T00:00:00.0Z,0,,STATUS,DeviceData\"\r\n\r\ndummyRecord=csv.from(csv: dummyRecordCsv )\r\n\r\nfirstStatusTimestampTemp=\r\n  from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n\r\nfirstStatusTimestamp=\r\n     union(tables: [firstStatusTimestampTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRangeTemp=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n\r\nlastStatusBeforeRange=\r\n     union(tables: [lastStatusBeforeRangeTemp,dummyRecord])\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n  |> cumulativeSum()\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Bad Items\"}))\r\n  |> cumulativeSum()\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> cumulativeSum()\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> cumulativeSum()\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n\r\n  \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\n\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\n\r\n\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n\r\nOEE\r\n|>yield(name: \"OEE\")\r\n\r\nAvailability\r\n|>yield(name: \"Availability\")\r\n\r\nQuality\r\n|>yield(name: \"Quality\")\r\n\r\nPerformance\r\n|>yield(name: \"Performance\")\r\n\r\n \r\n   \r\n RunStatus=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n     _field: \"Running\"\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: max)\r\n  |> yield(name: \"Run Status\") "
    }
   ]
  },
  {
   "title": "Throughput vs Quality",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit", "label": "%" }
   ],
   "targets": [
    {
     "query": "\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range([[range]])\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"[[Source]]\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n  |> yield(name: \"Good Items\")\r\n  |> cumulativeSum()\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({r with _field: \"Bad Items\"}))\r\n  |> yield(name: \"Bad Items\")\r\n  |> cumulativeSum()\r\n\r\n  \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\n\r\n\r\nQuality\r\n|>yield(name: \"Quality\")\r\n\n\r\nIdealRunrate=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"IdealRunrate\"\r\n    }))\r\n  |> yield(name: \"IdealRunrate\")\r\n \r\n  "
    }
   ]
  }
 ]
}