{
 "title": "Machine Level Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "${VAR_IDEALRUNRATE}" },
   {
    "name": "Source",
    "label": "Machine",
    "query": "from(bucket: \"telemetry\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r._measurement == \"DeviceData\"\n  )\n\n|> keep(columns:[\"Source\"])\n  |> distinct(column: \"Source\")\n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n   )\n|> group() \n\n\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\n\r\nRunningMins=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\n\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"Performance\"\r\n    }))\r\n|> yield(name: \"Performance\")\n"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "OEE%" }
   ],
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n  )\r\n  |> group()\r\n\n\r\nStatusData=\r\n  DeviceData\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n\nRunningMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n  \r\nIdleMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_BAD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n  |> map(fn: (r) => ({ r with _field: \"Bad Items\"}))\r\n\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\n\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"Performance\"\r\n    }))\n\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n\r  |> yield(name: \"OEE\")\n\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\"\r\n and r.Source == \"[[Source]]\"\r\n  )\r\n\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n\r\nRunningMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n |> truncateTimeColumn(unit: 1m)\r\n\r\n\r\nIdleMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n  \r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n|> yield(name: \"Availability\")\r\n"
    }
   ]
  },
  {
   "title": "Availability History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability%" }
   ],
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n  )\r\n\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n\r\nRunningMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n  \r\nIdleMins=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n\n\n\nRunStatus=\r\n  StatusData\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n     _field: \"Running\"\n    }))\r\n  |> aggregateWindow(every: 1m, fn: max)\r\n\nunion(tables: [RunStatus, Availability])\r\n|> keep(columns: [\"_field\",\"_value\",\"_time\"])\r\n|> group(columns:[\"_field\"], mode: \"by\")\r\n|>yield()\r\n\n"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n  )\r\n\r|> group()\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_BAD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time\r\n    }))\r\nQuality\n"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "Quality%" }
   ],
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n  )\r\n\r\r|> group()\n\r\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  \n  \n  \nItemCountGoodDataWindowed=\n  ItemCountGoodData\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n//  |> yield(name: \"Good Items\")\n\nItemCountGoodDataCumulative=\n  ItemCountGoodData\n  |> cumulativeSum()\n\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_BAD\"\r\n  )\n  |> aggregateWindow(every: 1m, fn: sum)\r\n\nItemCountBadDataWindowed=\r\n  ItemCountBadData\n  |> map(fn: (r) => ({ r with _field: \"Bad Items\"}))\r\n//  |> yield(name: \"Bad Items\")\n\nItemCountBadDataCumulative=  \n  ItemCountBadData\n  |> cumulativeSum()\n  |> map(fn: (r) => ({ r with _field: \"Bad Items\"}))\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodDataCumulative, bad: ItemCountBadDataCumulative},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r//  |> yield(name: \"Quality\")\n\nunion(tables: [ItemCountBadDataWindowed, ItemCountGoodDataWindowed, Quality])\r\n|> keep(columns: [\"_field\",\"_value\",\"_time\"])\r\n|> group(columns:[\"_field\"], mode: \"by\")\r\n|>yield()\r\n\n\nIdealRunrate=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"IdealRunrate\"\r\n    }))\r\n  |> yield(name: \"IdealRunrate\")\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n   )\n|> group() \n\n\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\n\r\nRunningMins=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n  |> truncateTimeColumn(unit: 1m)\r\n\n\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"Performance\"\r\n    }))\r\n|> yield(name: \"Performance\")\n"
    }
   ]
  },
  {
   "title": "Performance History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "Performance%" }
   ],
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range($range)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"DeviceData\" and \r\n    r.Source == \"[[Source]]\"\r\n  )\n  |> group()\n\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"ITEM_COUNT_GOOD\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\nRunningMins=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:$idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:$idealRunrate),\r\n     _time: r._time,\r\n     _field: \"Performance\"\r\n    }))\r\n|> yield(name: \"Performance\")\r\n\nIdealRunrate=\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:$idealRunrate),\r\n     _time: r._time,\n     _field: \"IdealRunrate\"\r\n    }))\n  |> yield(name: \"IdealRunrate\")\r"
    }
   ]
  }
 ]
}