{
 "title": "Site Level Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "1800" },
   {
    "name": "Source",
    "label": "Site",
    "query": "from(bucket: \"telemetry\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r._measurement == \"DeviceData\"\n  )\n\n|> keep(columns:[\"Source\"])\n  |> distinct(column: \"Source\")\n\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n    \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:v.idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n  |> yield(name: \"OEE\")\r\n"
    }
   ]
  },
  {
   "title": "OEE History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "OEE%" }
   ],
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> cumulativeSum()\r\n\r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> cumulativeSum()\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n    \r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:v.idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n\r\nAxQ=\r\n  join(\r\n    tables: {a:Availability, q: Quality},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_a * r._value_q,\r\n     _time: r._time,\r\n     _field: \"AxQ\"\r\n    }))\r\n\r\nOEE=\r\n  join(\r\n    tables: {axq:AxQ, p: Performance},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: r._value_axq * r._value_p,\r\n     _time: r._time,\r\n     _field: \"OEE\"\r\n    }))\r\n  |> yield(name: \"OEE\")\r\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n\r\n \r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n  \r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n  |> yield(name: \"Availability\")\r\n"
    }
   ]
  },
  {
   "title": "Availability History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability%" }
   ],
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n \r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> cumulativeSum()\r\n  \r\nIdleMins=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: 1.0 - r._value,\r\n     _time: r._time,\r\n    }))\r\n  |> cumulativeSum()\r\n\r\nAvailability=\r\n  join(\r\n    tables: {on: RunningMins, off: IdleMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on+r._value_off == 0.0 then 0.0 \r\n             else r._value_on/(r._value_on+r._value_off),\r\n     _time: r._time,\r\n     _field: \"Availability\"\r\n    }))\r\n  |> yield(name: \"Availability\")\r\n\r\n\r\nRunStatus=\r\n  StatusDataWindowed\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: r._time,\r\n     _field: \"Running\"\r\n    }))\r\n  |> aggregateWindow(every: 1m, fn: max)\r\n  |> yield(name: \"Run Status\")"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n \r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nItemCountBadData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodData, bad: ItemCountBadData},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n  |> yield(name: \"Quality\")\r\n"
    }
   ]
  },
  {
   "title": "Quality History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "Quality%" }
   ],
   "targets": [
    {
     "query": "DeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n \r\nItemCountGoodDataWindowed=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> map(fn: (r) => ({r with _field: \"Good Items\"}))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> yield(name: \"Good Items\")\r\n\r\nItemCountGoodDataCumulative=\r\n  ItemCountGoodDataWindowed\r\n  |> cumulativeSum()\r\n\r\nItemCountBadDataWindowed=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_BAD\" )\r\n  |> map(fn: (r) => ({r with _field: \"Bad Items\"}))\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> yield(name: \"Bad Items\")\r\n\r\nItemCountBadDataCumulative=\r\n  ItemCountBadDataWindowed\r\n  |> cumulativeSum()\r\n\r\nQuality=\r\n  join(\r\n    tables: {good: ItemCountGoodDataCumulative, bad: ItemCountBadDataCumulative},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_good+r._value_bad == 0.0 then 0.0 \r\n             else r._value_good/(r._value_good+r._value_bad),\r\n     _time: r._time,\r\n     _field: \"Quality\"\r\n    }))\r\n  |> yield(name: \"Quality\")\r\n\r\nIdealRunrate=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _field: \"IdealRunrate\"\r\n    }))\r\n  |> yield(name: \"IdealRunrate\")\r\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> sum()\r\n  |> map(fn: (r) => ({\r\n     _value: r._value,\r\n     _time: now()\r\n    }))\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:v.idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n  |> yield(name: \"Performance\")\r\n"
    }
   ]
  },
  {
   "title": "Performance History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "Performance%" }
   ],
   "targets": [
    {
     "query": "import \"math\"\r\nStatusValuesForOn = [101,105,108]\r\n\r\nfGetLastStatus = () => {\r\nfirstStatusTimestamp=\r\n  from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> filter(fn: (r) => r._field       == \"STATUS\" )\r\n  |> first()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_time\")\r\n\r\nlastStatusBeforeRange=\r\nfrom(bucket: \"telemetry\")\r\n  |> range(start:-1000d, \r\n           stop: time(v:uint(v:firstStatusTimestamp[0])-uint(v:1)))\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> map(fn: (r) => ({\r\n        _field: \"STATUS\",\r\n        _time: r._time, \r\n        _value: float(v: contains(value: int(v: r._value),\r\n                                  set  : StatusValuesForOn ))\r\n      }))\r\n  |> last()\r\n  |> tableFind(fn: (key) => key._field == \"STATUS\"  )\r\n  |> getColumn(column: \"_value\")         \r\n\r\nreturn lastStatusBeforeRange[length(arr:lastStatusBeforeRange)-1]\r\n}\r\n\r\nDeviceData=from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DeviceData\" )\r\n  |> filter(fn: (r) => r.Source       == \"v.Source\" )\r\n  |> group()\r\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\r\n\r\nItemCountGoodData=\r\n  DeviceData\r\n  |> filter(fn: (r) => r._field == \"ITEM_COUNT_GOOD\" )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> cumulativeSum()\r\n\r\nStatusData=\r\n  DeviceData\r\n  |> filter(fn: (r) =>  r._field == \"STATUS\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time, \r\n      _value: float(v: contains(value: int(v: r._value), \r\n                                       set: StatusValuesForOn ))\r\n  }))\r\n\r\nStatusDataWindowed=\r\n  StatusData\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> fill(column: \"_value\", usePrevious: true) \r\n  |> fill(column: \"_value\", value: fGetLastStatus()) \r\n  |> map(fn: (r) => ({_time: r._time, _value: math.ceil(x: r._value)}))\r\n  \r\nRunningMins=\r\n  StatusDataWindowed\r\n  |> cumulativeSum()\r\n\r\nPerformance=\r\n  join(\r\n    tables: {good: ItemCountGoodData, on: RunningMins},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n     _value: if r._value_on == 0.0 or float(v:v.idealRunrate) == 0.0 then 0.0 \r\n             else (r._value_good/r._value_on)/float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _value_on : r._value_on, _value_good: r._value_good,\r\n     _field: \"Performance\"\r\n    }))\r\n|> yield(name: \"Performance\")\r\n\r\nIdealRunrate=\r\n  DeviceData\r\n  |> filter(fn: (r) =>\r\n    r._field == \"STATUS\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> map(fn: (r) => ({\r\n     _value: float(v:v.idealRunrate),\r\n     _time: r._time,\r\n     _field: \"IdealRunrate\"\r\n    }))\r\n  |> yield(name: \"IdealRunrate\")"
    }
   ]
  }
 ]
}